Update `update_datasets` script
CONP-PCNO/conp-portal pull request #365
Opened 2020-11-11 21:24 UTC by liamocn

## Related issues

#155 

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose

This PR ensure the `update_datasets` script skips directories that are not in either the `/projects` or `/investigator` directories. An ERROR message was being thrown every time this script ran because of search for DATS files where they don't exist.

## Current behaviour

All subdirectories are searched for a DATS.json file including those where none are expected

## New behaviour

Only the `/projects` and `/investigators` directories are searched 
 
#### Does this introduce a major change?
- [ ] Yes
- [ ] No

## Implementation Detail

2020-11-13 14:53 UTC, xlecours requested changes

2020-11-13 14:53 UTC, xlecours commented on app/cli.py
> +        patterns = [app.config['DATA_PATH'] + '/conp-dataset/projects/*', app.config['DATA_PATH'] + '/conp-dataset/investigators/*']
you can remove investigator. It doesn't exists anymore. 
If we ever add it back we will change this line.

2020-11-18 16:06 UTC, cmadjar requested changes
@liamocn this is failing Travis. If you could also integrate Xavier's comment at the same time, that would be awesome. Thanks!

2020-11-20 15:12 UTC, cmadjar requested changes
one tiny change on the comment. Otherwise, looks good!!

2020-11-20 15:12 UTC, cmadjar commented on app/cli.py
> +        # The folowing relates to the DATS.json files of the projects.
```suggestion
        # The following relates to the DATS.json files of the projects directory in the conp-dataset repo.
```

2020-11-24 14:07 UTC, cmadjar approved these changes
LGTM

2020-11-24 14:08 UTC, merged