Add contextual help on each page
CONP-PCNO/conp-portal pull request #379
Opened 2020-11-27 04:55 UTC by haoweiqiu

## Related issues 

#206 

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose

Resolve issue #206.

## Current behaviour

 There is no help text provided by the portal.

## New behaviour

Help texts are provided.

#### Does this introduce a major change?
- [ ] Yes
- [x] No

## Implementation Detail

![page5](https://user-images.githubusercontent.com/42322196/100412415-a2121180-3042-11eb-8850-11d0fa4fcc19.png)
![page1](https://user-images.githubusercontent.com/42322196/100412383-8c045100-3042-11eb-887a-9f901482d6b9.png)
![page2](https://user-images.githubusercontent.com/42322196/100412404-99214000-3042-11eb-967d-e6078652ce66.png)
![page3](https://user-images.githubusercontent.com/42322196/100412405-9b839a00-3042-11eb-9bc6-5e7bdf7fa9c9.png)
![page4](https://user-images.githubusercontent.com/42322196/100412411-a0484e00-3042-11eb-8c01-7a2a6f714bdb.png)

2020-11-27 16:30 UTC, cmadjar requested changes
Thank you @haoweiqiu ! This is very nice!!

I suggested in the attached review some changes to the text of the help section. A few generic comments:
- Regarding the screenshots, did you take the images from the following [conp-documentation repo](https://github.com/CONP-PCNO/conp-documentation/tree/master/img)? Just to be sure they are the same. It looks like it is.
- in the edits I made, the image `app/static/img/Portal_access_from_conp.ca.png ` won't be displayed so it should be removed.
- split the help section of the search list and item pages into two for pipelines and datasets (more information provided in the inline comments)

Let me know once ready for another round of review. Thanks!

2020-11-27 16:30 UTC, cmadjar commented on app/templates/common/base_main.html
> +            <img src="/static/img/Dataset_download_instructions.png"alt="Portal_access_from_conp.ca" width="700px">
This part should not be in the data search page help section. I would instead modify it a little as follows and have that shown in the dataset specific page instead.

```suggestion
            <h4>Dataset Page</h4>
            <p>This page provides more detailed information regarding a dataset. This includes contact information, dataset version, descriptions, licenses, related publication and so on.</p>
            <p>Dataset download is available through DataLad. Each dataset page contains a detailed 
            ‘Dataset Download Instructions’ section that lay out the different steps to perform in order 
            to download the dataset.</p>
            <img src="/static/img/Dataset_download_instructions.png"alt="Portal_access_from_conp.ca" width="700px">
            <p>Finally, the dataset README file can be viewed at the end of the page.</p>
```

2020-11-27 16:30 UTC, cmadjar commented on app/templates/common/base_main.html
> +            <img src="/static/img/Pipeline_detailed_page.png"alt="Portal_access_from_conp.ca" width="700px">
Same general comment as for the dataset section. This should be divided in two: one tools & pipelines search to be displayed on this page and one specific to the pipeline page to be displayed on the pipeline page.

```suggestion
            <h4>Tools & Pipelines Search Page</h4>
            <p>The Tools & Pipelines Search page lists all softwares registered in the portal. Each tool 
            or pipeline present in that list page contains basic information about the tool/pipeline 
            and its pipeline ID.</p>
            <img src="/static/img/Pipeline_search_page.png"alt="Portal_access_from_conp.ca" width="700px">
            <p>Clicking on a specific choice will bring the user to a more detailed page with links 
            to instructions on how to run the tool locally, to HCPs or to external platforms.</p>
            <img src="/static/img/Pipeline_detailed_page.png"alt="Portal_access_from_conp.ca" width="700px">
```

2020-11-27 16:30 UTC, cmadjar commented on app/templates/common/base_main.html
> +            new tab with the instructions to follow to deploy a tool/pipeline on your Compute Canada account.</p>
This part should go into the pipeline specific page.

```suggestion
            <h4>Tool/Pipeline Page</h4>
            <p>The tool/pipeline detailed page displays all the information pertinent to the tool/pipeline. This includes authorship information, the descriptor URL, the container image information, the tool description and so on. In addition, the page provides information on how to run the tool locally or on HPCs via the CBRAIN platform or Clowdr.</p>
            <h6>Run the tool locally</h6>
            <p>Tools and pipelines can be run locally on any system using Boutiques and a container engine 
            (Docker or Singularity) based on the Zenodo ID of the tool. The container image for the tool is 
            listed in the detailed page of the tool/pipeline.</p>
            <p>At the bottom of the pipeline page, detailed instructions on how to run the tool locally 
            are available to the user.</p>
            <img src="/static/img/Boutiques_instructions.png"alt="Portal_access_from_conp.ca" width="700px">
            <p>If you have never used Boutiques in the past, we recommend the following tutorial.</p>
            <h6>Run the tool on HPCs</h6>
            <p>Some tools and pipelines can also be run on HPCs via the CBRAIN infrastructure or in 
            your Compute Canada account with Clowdr.</p>
            <img src="/static/img/CBRAIN_link_highlighted.png"alt="Portal_access_from_conp.ca" width="700px">
            <p>The 'Click here to begin' link under the 'Run on the CBRAIN Platform' container will open a 
            tab to the login page of CBRAIN or to your CBRAIN account if you are already logged in.</p>
            <p>The 'Click here for instructions' link under the 'Run on HPCs with Clowdr' will open a 
            new tab with the instructions to follow to deploy a tool/pipeline on your Compute Canada account.</p>
```

2020-11-27 16:30 UTC, cmadjar commented on app/templates/common/base_main.html
> +         Boutiques tutorial Python notebook.</p>
```suggestion
        <h4>Share Page</h4>
        <h5>How to Share Datasets and Pipelines Tab</h5>
        <p>This tab contains detailed technical instructions on how to upload your dataset or pipeline to CONP.</p> 
        <h6>Tool/Pipeline Upload</h6>
        <p>You can publish your tools/pipelines using Boutiques’ command bosh publish.</p>
        <p>For more information on how to do that, please visit the ‘Publishing your own tool’ section of the 
         Boutiques tutorial Python notebook.</p>
         <h6>Dataset Upload</h6>
        <p>A dataset can be uploaded to CONP via the following mechanisms:</p>
        <li>Through Zenodo by tagging your dataset with the keyword canadian-open-neuroscience-platform</li>
        <li>Through the Open Science Framework (OSF) by tagging your dataset with the keyword canadian-open-neuroscience-platform
         and setting the dataset to Public</li>
         <li>Through DataLad within the context of CONP</li>
         <h5>Create or Edit a DATS.json File Tab</h5>
         <p>Each dataset to be uploaded should contain a valid DATS.json descriptors derived from schema.org.
         We provide a DATS GUI editor that will create a DATS.json file to ease the creation process of the 
         DATS.json that will describe the dataset to be uploaded</p>
```

At the bottom of this help text, could you create a screenshot of the DATS GUI editor and show it after the short description of the editor?

2020-11-27 17:14 UTC, haoweiqiu commented
Hi @cmadjar, thank you very much for the comment. Yes, I took the images from the conp-documentation repo and I put the images under app/static since flask appears to consider this directory as default. I'll review your comment and modify soon.

2020-11-30 22:34 UTC, cmadjar requested changes
@haoweiqiu Thank you for the quick updates!

One thing to remove in the text content (see comment below).

Otherwise: one generic comment: is there a way to display the help content so that it does not block access to the portal page? So you could have the help open and keep scrolling and clicking on the page.

Thanks!

2020-11-30 22:34 UTC, cmadjar commented on app/templates/common/base_main.html
> +            <img src="/static/img/Dataset_download_instructions.png"alt="Dataset_download_instructions" width="700px">
```suggestion
```

2020-11-30 22:34 UTC, cmadjar commented on app/templates/common/base_main.html
> +            <img src="/static/img/Dataset_download_instructions.png"alt="Dataset_download_instructions" width="700px">
remove this since it is specific to the dataset page, not the search page

2020-12-04 15:38 UTC, cmadjar approved these changes
@liamocn also reviewed it and all good! Thank you @haoweiqiu :)

2020-12-04 19:57 UTC, merged

2020-12-04 21:57 UTC, haoweiqiu commented
@cmadjar Thank you very much!