New dataset and pipeline card layout
CONP-PCNO/conp-portal pull request #540
Opened 2022-05-11 21:41 UTC by cmadjar

The dataset and pipeline cards have been redesigned in this PR as discussed in the past few weeks during the CONP dev calls.

Changes include:
- refactoring of the download and process columns into buttons:
  - one button for direct download
  - one button for the link to the DataLad instructions for download
  - one button to process on CBRAIN
- addition of circled question mark with tooltips next to the following features to provide users with more explanation of the feature:
  - for the "Direct Download" button
  - for the "Download With DataLad" button
  - for the "Process On CBRAIN" button
  - for the "Metadata file" download link
- harmonization of the look of the dataset and pipeline cards
- moved the download metadata into the detailed page

New layout for a dataset:
![Screen Shot 2022-05-11 at 5 40 58 PM](https://user-images.githubusercontent.com/1402456/167952523-7b96012b-80d5-42a8-99db-8066611ebed9.png)

New card layout for a tool:
![Screen Shot 2022-05-11 at 5 41 21 PM](https://user-images.githubusercontent.com/1402456/167952562-a45e3ffa-180d-42c7-b5e1-5342859e8cfc.png)

2022-05-11 21:42 UTC, cmadjar commented
@tkkuehn I am still waiting for feedbacks from Patrick about the text of the tooltips which is why I marked the PR as blocked but maybe you could review the rest and test in the meantime?

Thank you!!

2022-05-12 15:54 UTC, tkkuehn requested changes
A few relatively minor changes but this overall looks great, thanks for putting it together!

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/index.js
> +              <p className="card-text pl-1">
Maybe make this a `div`? React complains for me in the dev console about having a `ReactToolTip` as a descendant of a `p`.

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/index.js
> +              <p className="card-text pl-1">
Maybe make this a `div`? React complains for me in the dev console about having a `ReactToolTip` as a descendant of a `p`.

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/index.js
> +              <p className="card-text pl-1">
Maybe make this a `div`? React complains for me in the dev console about having a `ReactToolTip` as a descendant of a `p`.

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/PipelineElement/index.js
> +        <p className="card-text pl-1">
Maybe change this to `div`.

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/PipelineElement/index.js
> +              className="cbrain-img justify-content-center align-items-center pl-4"
Add something like `alt="CBRAIN logo"`

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/PipelineElement/index.js
> +              <img
Add something like `alt="Disabled CBRAIN logo"`

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/DownloadModalWindowElement/index.js
> +             <img src="static/img/conp.png" className="text-center" style={{width:"100%"}}/>
Add something like `alt="CONP logo"`

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/DownloadModalWindowElement/index.js
> +import React, { useState } from "react";
`useState` isn't used.

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/DownloadModalWindowElement/index.js
> +  const { authorized, imagePath, ...element } = props;
I think only `element.size` and `element.zipLocation` are used, so we could just pass those two directly and use a lot fewer props for this component.

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/DownloadModalWindowElement/index.js
> +DownloadModalWindowElement.propTypes = {
Again, we could get rid of most of these props.

2022-05-12 15:54 UTC, tkkuehn commented on app/static/lib/conp-react/src/DatasetElement/DownloadModalWindowElement/index.js
> +        <table>
I would rather use a bootstrap container for laying out the CONP image and warning text if we could.

2022-05-12 21:33 UTC, cmadjar commented
@tkkuehn thank you for all the great suggestions! I should have addressed all of them. Ready for another look and test :-).

FYI - the tooltip texts have also been updated.

Thanks again!!

2022-05-13 13:10 UTC, tkkuehn approved these changes

2022-05-16 13:18 UTC, merged